name: Run tests and lint

on: [push]

permissions:
  contents: read

jobs:
  build_and_test_and_lint:
    name: Build test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
      - name: Go get
        run: go get -t -v ./...
      - name: Check formatting
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Run go vet
        run: go vet .
      - name: Run tests
        run: go test -v -race ./...
      - name: Run the binary on the README file
        run: diff -u <(echo -n) <(markdownfmt -d README.md)
